language: python
sudo: true
python:
- '3.6'
addons:
  postgresql: '9.4'
cache: pip
before_install:
- psql -c 'create database "newamerica";' -U postgres
services:
- elasticsearch
before_script:
- sleep 10
install:
- travis_retry pip install --upgrade setuptools
- travis_retry pip install -r requirements.txt
- travis_retry npm install
- STATIC_URL="https://fake.io" npm run build:production
script:
- python manage.py migrate --noinput --settings=newamericadotorg.settings.test
- python manage.py test --noinput --settings=newamericadotorg.settings.test
deploy:
  provider: heroku
  api_key:
    secure: lk+Hz2BpV+/fCOHR0UkxS8fwRZI+0BLgDteWeyRtdHaQ9buRRtm1PEAbD+WXvemqH1qDe1sKdxkGLsfV1kdyil4uQ1eutg7YYM2ZYHUtml6qSOgykayEuvK/+yUTaE64ZhiZaf9oJVFNJTjBxW7YW790Oxxow3v/Jve0iR/zgmJU0j04qqaMp+XdF2QsdUFdKHC9dQiQESuVw4ugtpsaka0wvLL+fPs2d1TlkBnJjWFJqNgBUVyfejl7gsTzm/DgOVeiqQD1fkectobvu93fKYu3PFbrZTYYq2ag8DZe0FJ1fv6q4QDslPHJtwVQwzbSmP2MBWXFhq86+JZ8mmX/rRvBI6pdbiWSq8gS6pVS0RZDwC+/1vOEhchBcA9Sks80f7Zsoa6bqFpAMR86gRzsYNtHHzmCuH76difPTrT3ReS+pNkeFexSaDYKRJqTv+a228pqcnyH48MUjERasn5hX9FYdezTVEDtbN0qSwvlWYBkGPfOqUoABbh+DQF2I7TQo9NkEsrdQHxru3U9LAku8JEvzaxoyKtPzWpgv2CAN15ZqB71290DHALsxeZI0cBAipRF/sW4a3Q2qxnNUcyw4wmpjrd07/AScj8LnCvbB7DdL76JWpIu/KKX61Yi4ai8kFmKkoLYN5WPGi3m+YB+EkLLwi6pf4+q5hUKCYmLq6M=
    app:
      staging: na-staging
notifications:
  slack:
    secure: BB9OPeZYwNLTYCGE4BChCot9iOGOKp9DMKCRUKacthp0k2YFQuBni81WC9ECiY6msXEsYh3B+2B1Lu1L8MoelqGuXeT8x0EnOgEphAtUtx7LXsWlezVceu6I4FW4JnVlgMY/mHFHWAuuexnMZq8rQ0EHiRC9aBUbw5/FjyyHmnk1q6Mf0QwOb8OXBrTtblNmtRqQ5go91AeDvqBYxSXKWwrZj/6DrtRVDasHOTsCMy2chAM/azJEWMXfnWmUvWR2XwnW8Ohxl+woqLogLpx0xAgkAFydqZkoDRUCIq3kicWYSN1IY3EYAjrLdfaWDMmTa/yhkI5uJ6mVPw7AqCEj27DYk7fOPGmr004zSslAT0PBBsB2luO7/lUaM5ohdrtZQYjotIcYU6+nf8nwSSE/r3eSC8feNfOD72rJ4RK3VVZgQKZDO7XSmtMlGnTUDE/YDCuKhmS/tAZ6RvO4gbdJLD+L5T+koAARKRPhtHJg+RDIWXgh30KVT0pz8fmxUnJInPxoHlAuspXBatiBsSz4nH/kkffAVTgDsSUQUF6rvBVx+VFcId5VdIjoFVD+Ib9PIijGoD43xJFu/fiG49i76P21FBjH4NjMOsc3/u3b/fUIuZZ9/UhyyXMP44GjBxjE0GheAjZ+MJpcvby+A5AeP+dhagTN7BfhxB998GKnv58=
