language: python
sudo: true
python:
- '3.6'
addons:
  postgresql: '9.4'
cache: pip
before_install:
- psql -c 'create database "newamerica";' -U postgres
services:
- elasticsearch
before_script:
- sleep 10
install:
- travis_retry pip install --upgrade setuptools
- travis_retry pip install -r requirements.txt
- travis_retry npm install
- STATIC_URL="https://fake.io" npm run build:production
script:
- python manage.py migrate --noinput --settings=newamericadotorg.settings.test
- python manage.py test --noinput --settings=newamericadotorg.settings.test
deploy:
  provider: heroku
  api_key:
    staging:
      secure: FSnlbLKRB+sSQG3GIxV/3D6WQrehqg8+t+H8r6pPLVZEV13Q+k7N8SqZ2dhr2hVCaBLfRBvduo+lfWwKEVfVoJIuuZgCg/PxUyH3+57tWCN2QjCp8Gq7NjcQYlHs32ev1dQqCEKVxnk+Yo/esl1RZ57fh4w2F4QLF4bazsldFDZCOyT79R5iqU8ucVkpGi+sSxP2h2Tu9AU+YIumLj+TLWd5keQWwj/QCHSz7vVPchBzx70DzVGo047yJcYjOxU0Eav+EoRaGuEHciCxYmKuhMZduIudnJXigG5G7TwcisdP4tAP88uuk2X2YkKZQXIkm8YLBALxzBYWCqgZZPRRELJk3PEVPJMP7QswK3i5bHUk9Uwv8C/xZnl6gDlLasQ1D2ZVOBA51iFpi6X60O/yFKwAY7HIXeU3Tne2MW7Hv3kw1tOsYw+t19ElKf8D1NMznD6MPmPCHfVTthKsW85GpXKSvg3SnE9O5h4AjQMYA7k8ezrWKFbeBCGE0gFXYInb1lFB3Toyifjv/k18cZpTh5HUIoCINcbJSSuOaC4Ls5usafQQFzU42Kh8U3Yh9OVqs1dPEz9JJx0N69zexLBkWXoczkAIX6BnwvN7cKbTV7etugjrG1ZutVIGNr6qhvH8ilbCrYnRPp0WY9RZm6tDIcv8e0XSAw/KAwyjeZKViCU=
  app:
    staging: na-staging
  on:
    branch: staging
notifications:
  slack:
    secure: BB9OPeZYwNLTYCGE4BChCot9iOGOKp9DMKCRUKacthp0k2YFQuBni81WC9ECiY6msXEsYh3B+2B1Lu1L8MoelqGuXeT8x0EnOgEphAtUtx7LXsWlezVceu6I4FW4JnVlgMY/mHFHWAuuexnMZq8rQ0EHiRC9aBUbw5/FjyyHmnk1q6Mf0QwOb8OXBrTtblNmtRqQ5go91AeDvqBYxSXKWwrZj/6DrtRVDasHOTsCMy2chAM/azJEWMXfnWmUvWR2XwnW8Ohxl+woqLogLpx0xAgkAFydqZkoDRUCIq3kicWYSN1IY3EYAjrLdfaWDMmTa/yhkI5uJ6mVPw7AqCEj27DYk7fOPGmr004zSslAT0PBBsB2luO7/lUaM5ohdrtZQYjotIcYU6+nf8nwSSE/r3eSC8feNfOD72rJ4RK3VVZgQKZDO7XSmtMlGnTUDE/YDCuKhmS/tAZ6RvO4gbdJLD+L5T+koAARKRPhtHJg+RDIWXgh30KVT0pz8fmxUnJInPxoHlAuspXBatiBsSz4nH/kkffAVTgDsSUQUF6rvBVx+VFcId5VdIjoFVD+Ib9PIijGoD43xJFu/fiG49i76P21FBjH4NjMOsc3/u3b/fUIuZZ9/UhyyXMP44GjBxjE0GheAjZ+MJpcvby+A5AeP+dhagTN7BfhxB998GKnv58=
