language: python
sudo: true
python:
- '3.6'
addons:
  postgresql: '9.4'
cache: pip
before_install:
- psql -c 'create database "newamerica";' -U postgres
services:
- elasticsearch
before_script:
- sleep 10
install:
- travis_retry pip install --upgrade setuptools
- travis_retry pip install -r requirements.txt
- travis_retry npm install
- STATIC_URL="https://fake.io" npm run build:production
script:
- python manage.py migrate --noinput --settings=newamericadotorg.settings.test
- python manage.py test --noinput --settings=newamericadotorg.settings.test
deploy:
  provider: heroku
  api_key:
    staging:
      secure: SRUQdvVeoCR8pMvxRhiWXtkOcAh7gMSbl9YwD1PIyP2iwkBIwsgP+nhjsLXTMQyuFYNsbUXIM4znmGkxjbDThiMikC1V5+/upI5qpyHoSBLMPbQ1Xzz8zeEDtKNW9TFh/Si+fKGkXBb2Y8jeNeJk7IPnezfbAVAVHga3oVMIe1q9CanUsY1yuZFDxT8UbCrjA/dyEV6Zq29XbiotMkqr2bJEch2b4CPlSDzhy2LPWHEXM6U8P/QxvcUCBRqOW662MS7rqErVFKb6kN7Yu8bfyZ0Dw3ctxMulY900S4UUo/vcfugpDEB4/cORZF3heXDNAO7knSUtINaxEYPQUA6fTS5idsOGEO03V9eVav/MoW5cpd0yPEwaWEg5L2huvY7Jw3wRsJMedDyaKHEf4MoW0Pb7SqZ6d83Lhlckp2e4HZuwrDx0t2jFCxsWHZOLychpRnym5D0Fk8UPadlaS5kF7l7wzZBTCC1r7lrg8ahZvcIO/tMwK2e92H4UBk2tVdbap1FrUT5JjIrqvvDA/1E05p9yuawDoybmVLrYJcCddjWembJQTResd53fyVOON85lIjZUr0uoxEG3b+D+/bp6WPDYlpK+VES5HRM1X42FFPLhJHSNNj4444WlL3UoRoCWaunQk86PAQ4AcOupKj1hzkCfVYYi78GjZKYESG9Gi34=
  app:
    staging: na-staging
  on:
    branch: staging
notifications:
  slack:
    secure: BB9OPeZYwNLTYCGE4BChCot9iOGOKp9DMKCRUKacthp0k2YFQuBni81WC9ECiY6msXEsYh3B+2B1Lu1L8MoelqGuXeT8x0EnOgEphAtUtx7LXsWlezVceu6I4FW4JnVlgMY/mHFHWAuuexnMZq8rQ0EHiRC9aBUbw5/FjyyHmnk1q6Mf0QwOb8OXBrTtblNmtRqQ5go91AeDvqBYxSXKWwrZj/6DrtRVDasHOTsCMy2chAM/azJEWMXfnWmUvWR2XwnW8Ohxl+woqLogLpx0xAgkAFydqZkoDRUCIq3kicWYSN1IY3EYAjrLdfaWDMmTa/yhkI5uJ6mVPw7AqCEj27DYk7fOPGmr004zSslAT0PBBsB2luO7/lUaM5ohdrtZQYjotIcYU6+nf8nwSSE/r3eSC8feNfOD72rJ4RK3VVZgQKZDO7XSmtMlGnTUDE/YDCuKhmS/tAZ6RvO4gbdJLD+L5T+koAARKRPhtHJg+RDIWXgh30KVT0pz8fmxUnJInPxoHlAuspXBatiBsSz4nH/kkffAVTgDsSUQUF6rvBVx+VFcId5VdIjoFVD+Ib9PIijGoD43xJFu/fiG49i76P21FBjH4NjMOsc3/u3b/fUIuZZ9/UhyyXMP44GjBxjE0GheAjZ+MJpcvby+A5AeP+dhagTN7BfhxB998GKnv58=
