language: python

sudo: true

python:
  - "3.4"

addons:
  postgresql: "9.4"

cache: pip

before_install:
  - psql -c 'create database "newamerica";' -U postgres

install:
  - travis_retry pip install dj-database-url==0.3.0
  - travis_retry pip install psycopg2==2.6
  - travis_retry pip install Django==1.9
  - travis_retry pip install wagtail==1.4.3
  - travis_retry pip install django-storages==1.4
  - travis_retry pip install django-compressor==2.0


script:
  - python manage.py migrate --noinput --settings=mysite.settings.test
  - python manage.py test --noinput --settings=mysite.settings.test
