language: python

sudo: true

python:
- '3.6'

addons:
  postgresql: '9.4'

cache: pip

before_install:
- psql -c 'create database "newamerica";' -U postgres

services:
  - elasticsearch

before_script:
  - sleep 10

install:
- travis_retry pip install --upgrade setuptools
- travis_retry pip install -r requirements.txt

script:
- python manage.py migrate --noinput --settings=newamericadotorg.settings.test
- python manage.py test --noinput --settings=newamericadotorg.settings.test
